name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  # pre-ci:
  #   name: Pre-CI
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up matrix
  #       id: set-matrix
  #       # Find all relevant files under .github/build-ci/manifests
  #       # then output them as a JSON array (minus the last comma)
  #       run: |
  #         files=$(find .github/build-ci/manifests/ -iname '*.j2' -printf '"%p",')
  #         echo "matrix=[${files%,}]" >> $GITHUB_OUTPUT

  ci:
    name: CI
    # needs: pre-ci
    # strategy:
    #   fail-fast: false
    #   max-parallel: 5
    #   matrix:
    #     file: ${{ fromJson(needs.pre-ci.outputs.matrix) }}
    uses: access-nri/build-ci/.github/workflows/ci.yml@264-get-manifest-from-any-repo
    with:
      spack-manifest-repository: codegat-test-org/test
      spack-manifest-repository-ref: 76f45ff6ea4694b5d1abce3b866e1b1d20ce4c4a
      spack-manifest-path: build-ci-manifests/intel.spack.yaml.j2
      allow-ssh-into-spack-install: false  # If true, PR author must ssh into instance to complete job
      spack-manifest-data-path: build-ci-manifests/standard.json
      # builtin-spack-packages-ref: main
      # access-spack-packages-ref: api-v2
      # spack-config-ref: main
      # spack-ref: releases/v1.1
